const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('lockdownreport')
    .setDescription('Generate a lockdown report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
  cooldown: 5,
  aliases: ['ldreport', 'lockdownsummary'],
  prefix: true,
  ownerOnly: true,
  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;
    const guild = interaction.guild;

    if (!member || !member.permissions.has(PermissionFlagsBits.Administrator)) {
      const embed = new EmbedBuilder()
        .setColor(0xed4245)
        .setDescription('You need Administrator permission to use this command.');
      return interaction.reply({ embeds: [embed] });
    }

    try {
      const report = securityEngine.generateReport(guild.id);
      const incidents = securityEngine.getIncidents(guild.id, 50);
      const stage = securityEngine.getStage(guild.id);

      const lockdownIncidents = incidents.filter(i =>
        i.type.includes('lockdown') || i.type.includes('freeze') || i.type.includes('stage_change')
      );

      const recentLockdowns = lockdownIncidents.slice(0, 5);
      const totalLockdownTime = lockdownIncidents.reduce((acc, inc) => {
        if (inc.type === 'freeze_activated') acc += Date.now() - inc.timestamp;
        return acc;
      }, 0);

      const embed = new EmbedBuilder()
        .setTitle('📊 Lockdown Report')
        .setDescription(`Comprehensive lockdown report for **${guild.name}**.`)
        .setColor(0x5865f2)
        .setTimestamp()
        .setFooter({ text: `Generated by ${user.tag}`, iconURL: user.displayAvatarURL() })
        .addFields(
          { name: 'Current Stage', value: `${stage.name} (Stage ${stage.stage})`, inline: true },
          { name: 'Total Incidents', value: `${report.totalIncidents}`, inline: true },
          { name: 'Unresolved', value: `${report.unresolvedIncidents}`, inline: true },
          { name: 'Join Velocity', value: `${report.joinVelocity.count} joins (${report.joinVelocity.velocity.toFixed(1)}/min)`, inline: true },
          { name: 'Risk Distribution', value: `🔴 Critical: ${report.riskSummary.critical}\n🟠 High: ${report.riskSummary.high}\n🟡 Medium: ${report.riskSummary.medium}\n🟢 Low: ${report.riskSummary.low}`, inline: false }
        );

      if (recentLockdowns.length > 0) {
        const lockdownList = recentLockdowns.map(inc =>
          `• **${inc.type}** — <t:${Math.floor(inc.timestamp / 1000)}:R> (${inc.userId})`
        ).join('\n');
        embed.addFields({ name: '🔒 Recent Lockdown Events', value: lockdownList, inline: false });
      } else {
        embed.addFields({ name: '🔒 Recent Lockdown Events', value: 'No recent lockdown events.', inline: false });
      }

      if (report.recommendations.length > 0) {
        const recs = report.recommendations.map(r => `• ${r}`).join('\n');
        embed.addFields({ name: '💡 Recommendations', value: recs, inline: false });
      }

      securityEngine.logIncident(guild.id, user.id, 'lockdown_report_generated', {
        totalIncidents: report.totalIncidents,
        unresolved: report.unresolvedIncidents,
        stage: stage.stage
      });

      await interaction.reply({ embeds: [embed] });
    } catch (error) {
      console.error(error);
      const embed = new EmbedBuilder()
        .setTitle('❌ Error')
        .setDescription('Failed to generate lockdown report.')
        .setColor(0xff0000)
        .setTimestamp();
      await interaction.reply({ embeds: [embed] });
    }
  }
};
