const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('antinukereport2')
    .setDescription('Generate antinuke report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
    .addStringOption(opt =>
      opt.setName('type')
        .setDescription('Type of report')
        .setRequired(false)
        .addChoices(
          { name: 'Summary', value: 'summary' },
          { name: 'Detailed', value: 'detailed' },
          { name: 'Security', value: 'security' }
        )
    ),

  cooldown: 15,
  aliases: ['anreport2', 'areport2'],
  prefix: true,
  ownerOnly: true,

  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;

    if (!member || !member.permissions.has(PermissionFlagsBits.Administrator)) {
      const embed = new EmbedBuilder()
        .setColor(0xff0000)
        .setTitle('Permission Denied')
        .setDescription('You need Administrator permission to use this command.')
        .setTimestamp();
      return interaction.reply({ embeds: [embed] });
    }

    const type = isSlash ? (interaction.options.getString('type') || 'summary') : (args[0] || 'summary');

    try {
      await interaction.deferReply();
      const report = securityEngine.generateReport(interaction.guild.id);

      const embed = new EmbedBuilder()
        .setColor(0x0099ff)
        .setTitle(`Antinuke Report - ${type.charAt(0).toUpperCase() + type.slice(1)}`)
        .setDescription(`Report generated for **${interaction.guild.name}**`)
        .setTimestamp();

      if (type === 'summary' || type === 'detailed') {
        embed.addFields(
          { name: 'Server', value: interaction.guild.name, inline: true },
          { name: 'Generated By', value: user.tag, inline: true },
          { name: 'Report Type', value: type.charAt(0).toUpperCase() + type.slice(1), inline: true },
          { name: 'Total Incidents', value: String(report?.totalIncidents || 0), inline: true },
          { name: 'Unresolved Incidents', value: String(report?.unresolvedIncidents || 0), inline: true },
          { name: 'Active Decoys', value: String(report?.activeDecoys || 0), inline: true },
          { name: 'Total Decoys', value: String(report?.totalDecoys || 0), inline: true },
          { name: 'Current Stage', value: report?.currentStage?.name || 'Normal', inline: true }
        );
      }

      if (type === 'detailed' || type === 'security') {
        if (report?.recentIncidents?.length) {
          const incidents = report.recentIncidents.slice(0, 5).map(i =>
            `\`${new Date(i.timestamp).toLocaleString()}\` ${i.type}`
          ).join('\n');
          embed.addFields({ name: 'Recent Incidents', value: incidents });
        }

        if (report?.riskSummary) {
          const rs = report.riskSummary;
          embed.addFields({
            name: 'Risk Summary',
            value: `Critical: ${rs.critical || 0}\nHigh: ${rs.high || 0}\nMedium: ${rs.medium || 0}\nLow: ${rs.low || 0}`,
            inline: true
          });
        }

        if (report?.recommendations?.length) {
          const recs = report.recommendations.map(r => `• ${r}`).join('\n');
          embed.addFields({ name: 'Recommendations', value: recs });
        }

        if (report?.joinVelocity) {
          const jv = report.joinVelocity;
          embed.addFields({
            name: 'Join Velocity',
            value: `Count: ${jv.count || 0}\nVelocity: ${(jv.velocity || 0).toFixed(1)}/min\nRisk: ${jv.riskLevel || 'low'}`,
            inline: true
          });
        }
      }

      return interaction.editReply({ embeds: [embed] });
    } catch (error) {
      const embed = new EmbedBuilder()
        .setColor(0xff0000)
        .setTitle('Report Error')
        .setDescription(`Failed to generate report: ${error.message}`)
        .setTimestamp();
      if (interaction.deferred) {
        return interaction.editReply({ embeds: [embed] });
      }
      return interaction.reply({ embeds: [embed] });
    }
  }
};
