const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('behaviorreport')
    .setDescription('Generate behavior analysis report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
  cooldown: 5,
  aliases: ['breport', 'behaviorsummary'],
  prefix: true,
  ownerOnly: true,
  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;
    const guild = interaction.guild;

    if (!member || !member.permissions.has(PermissionFlagsBits.Administrator)) {
      const embed = new EmbedBuilder()
        .setColor(0xed4245)
        .setDescription('You need Administrator permission to use this command.');
      return interaction.reply({ embeds: [embed] });
    }

    try {
      const profiles = [...securityEngine.profiles.values()].filter(p => p.guildId === guild.id && !p.userId.includes(':'));
      const incidents = securityEngine.getIncidents(guild.id, 200);

      let totalMessages = 0;
      let totalEdits = 0;
      let totalDeletes = 0;
      let totalAnomalies = 0;
      let totalKicks = 0;
      let totalBans = 0;
      let totalChannelCreates = 0;
      let totalChannelDeletes = 0;
      let totalPermissionEscalations = 0;
      const riskScores = [];

      for (const profile of profiles) {
        totalMessages += profile.messageCount;
        totalEdits += profile.editCount;
        totalDeletes += profile.deleteCount || 0;
        totalAnomalies += profile.anomalies.length;
        totalKicks += profile.memberKicks;
        totalBans += profile.memberBans;
        totalChannelCreates += profile.channelCreates;
        totalChannelDeletes += profile.channelDeletes;
        totalPermissionEscalations += profile.permissionEscalations;

        const risk = securityEngine.calculateRisk(guild.id, profile.userId);
        riskScores.push(risk);
      }

      const avgRisk = riskScores.length > 0 ? (riskScores.reduce((a, b) => a + b, 0) / riskScores.length).toFixed(1) : 0;
      const maxRisk = riskScores.length > 0 ? Math.max(...riskScores) : 0;
      const riskDistribution = {
        critical: riskScores.filter(r => r > 75).length,
        high: riskScores.filter(r => r > 50 && r <= 75).length,
        medium: riskScores.filter(r => r > 25 && r <= 50).length,
        low: riskScores.filter(r => r <= 25).length
      };

      const behaviorIncidents = incidents.filter(i =>
        i.type.includes('anomaly') || i.type.includes('behavior') || i.type.includes('burst') || i.type.includes('raid')
      );

      const last24hIncidents = behaviorIncidents.filter(i => Date.now() - i.timestamp < 86400000);

      const embed = new EmbedBuilder()
        .setTitle('📊 Behavior Analysis Report')
        .setDescription(`Comprehensive behavioral analysis report for **${guild.name}**.`)
        .setColor(0x5865f2)
        .setTimestamp()
        .setFooter({ text: `Generated by ${user.tag}`, iconURL: user.displayAvatarURL() })
        .addFields(
          { name: '👥 Profiles Analyzed', value: `${profiles.length}`, inline: true },
          { name: '📊 Average Risk', value: `${avgRisk}/100`, inline: true },
          { name: '⚠️ Max Risk', value: `${maxRisk}/100`, inline: true }
        )
        .addFields(
          { name: '💬 Message Stats', value: `Total: **${totalMessages}**\nEdits: **${totalEdits}**\nDeletes: **${totalDeletes}**`, inline: true },
          { name: '🔧 Mod Actions', value: `Kicks: **${totalKicks}**\nBans: **${totalBans}**\nRole Changes: **${totalPermissionEscalations}**`, inline: true },
          { name: '📢 Channel Activity', value: `Creates: **${totalChannelCreates}**\nDeletes: **${totalChannelDeletes}**\nAnomalies: **${totalAnomalies}**`, inline: true }
        )
        .addFields({
          name: '⚠️ Risk Distribution',
          value: `🔴 Critical (>75): **${riskDistribution.critical}**\n🟠 High (50-75): **${riskDistribution.high}**\n🟡 Medium (25-50): **${riskDistribution.medium}**\n🟢 Low (<25): **${riskDistribution.low}**`,
          inline: false
        });

      if (last24hIncidents.length > 0) {
        embed.addFields({
          name: '🕐 Recent Activity (24h)',
          value: `**${last24hIncidents.length}** behavior-related incidents.`,
          inline: false
        });
      }

      const recommendations = securityEngine.generateRecommendations(guild.id, incidents);
      if (recommendations.length > 0) {
        const recs = recommendations.map(r => `• ${r}`).join('\n');
        embed.addFields({ name: '💡 Recommendations', value: recs, inline: false });
      }

      securityEngine.logIncident(guild.id, user.id, 'behavior_report_generated', {
        profiles: profiles.length,
        avgRisk,
        totalAnomalies,
        totalMessages
      });

      await interaction.reply({ embeds: [embed] });
    } catch (error) {
      console.error(error);
      const embed = new EmbedBuilder()
        .setTitle('❌ Error')
        .setDescription('Failed to generate behavior report.')
        .setColor(0xff0000)
        .setTimestamp();
      await interaction.reply({ embeds: [embed] });
    }
  }
};
