const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('forensicreport')
    .setDescription('Generate a detailed forensics report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
    .addStringOption(opt =>
      opt.setName('format').setDescription('Report format')
        .addChoices(
          { name: 'Summary', value: 'summary' },
          { name: 'Detailed', value: 'detailed' },
          { name: 'Timeline', value: 'timeline' }
        )
    ),
  cooldown: 5,
  aliases: ['frpt', 'forensicrpt'],
  prefix: true,
  ownerOnly: true,
  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;
    const guild = interaction.guild;

    try {
      if (!member || !member.permissions.has(PermissionFlagsBits.Administrator)) {
        const embed = new EmbedBuilder()
          .setColor(0xed4245)
          .setDescription('You need Administrator permission to use this command.');
        return interaction.reply({ embeds: [embed] });
      }

      const format = isSlash
        ? interaction.options.getString('format')
        : (args[0] || 'summary').toLowerCase();

      const report = securityEngine.generateReport(guild.id);
      const incidents = securityEngine.getIncidents(guild.id, 200);
      const stage = securityEngine.getStage(guild.id);

      let color = 0x0099ff;
      if (report.riskSummary.critical > 0) color = 0xff0000;
      else if (report.riskSummary.high > 0) color = 0xff6600;

      const embed = new EmbedBuilder()
        .setTitle(`📋 Forensic Report — ${format.charAt(0).toUpperCase() + format.slice(1)}`)
        .setDescription(`Generated by ${user.tag} at <t:${Math.floor(Date.now() / 1000)}:F>`)
        .setColor(color)
        .setTimestamp()
        .setFooter({ text: `Guild: ${guild.name}`, iconURL: guild.iconURL() });

      embed.addFields({
        name: '🛡️ Security Posture',
        value: `Current Stage: **${stage.name}** (${stage.stage})\nTotal Incidents: **${report.totalIncidents}**\nUnresolved: **${report.unresolvedIncidents}**`,
        inline: true
      });

      embed.addFields({
        name: '📊 Risk Distribution',
        value: `🔴 Critical: **${report.riskSummary.critical}**\n🟠 High: **${report.riskSummary.high}**\n🟡 Medium: **${report.riskSummary.medium}**\n🟢 Low: **${report.riskSummary.low}**`,
        inline: true
      });

      embed.addFields({
        name: '🪤 Decoy Status',
        value: `Active: **${report.activeDecoys}**\nTotal: **${report.totalDecoys}**`,
        inline: true
      });

      if (format === 'detailed' || format === 'timeline') {
        if (format === 'timeline') {
          const timelineIncidents = incidents.slice(0, 15);
          if (timelineIncidents.length > 0) {
            const timeline = timelineIncidents.map(i => {
              const icon = i.type === 'anomaly_detected' ? '⚠️' :
                i.type === 'decoy_triggered' ? '🪤' :
                  i.type === 'stage_change' ? '🔄' : '📋';
              return `${icon} **${i.type}** — <t:${Math.floor(i.timestamp / 1000)}:R>\n> ${securityEngine.explainThreat(i)}`;
            }).join('\n\n');

            embed.addFields({
              name: '🕐 Incident Timeline',
              value: timeline.substring(0, 2048),
              inline: false
            });
          }
        }

        if (format === 'detailed') {
          const userRisk = [];
          guild.members.cache.forEach(m => {
            if (m.user.bot) return;
            const risk = securityEngine.calculateRisk(guild.id, m.id);
            if (risk > 30) userRisk.push({ member: m, risk });
          });
          userRisk.sort((a, b) => b.risk - a.risk);

          if (userRisk.length > 0) {
            const riskList = userRisk.slice(0, 10).map((u, i) =>
              `**${i + 1}.** ${u.member.user.tag} — Risk: **${u.risk}**/100`
            ).join('\n');

            embed.addFields({
              name: '⚠️ User Risk Profile',
              value: riskList.substring(0, 1024),
              inline: false
            });
          }
        }
      }

      if (report.recommendations.length > 0) {
        embed.addFields({
          name: '💡 Recommendations',
          value: report.recommendations.map(r => `• ${r}`).join('\n'),
          inline: false
        });
      }

      const recentEvents = incidents.slice(0, 5);
      if (recentEvents.length > 0) {
        const eventList = recentEvents.map(e =>
          `• ${securityEngine.explainThreat(e)} — <t:${Math.floor(e.timestamp / 1000)}:R>`
        ).join('\n');

        embed.addFields({
          name: '📋 Recent Events',
          value: eventList.substring(0, 1024),
          inline: false
        });
      }

      securityEngine.logIncident(guild.id, user.id, 'forensic_report_generated', {
        format,
        incidentCount: incidents.length
      });

      return interaction.reply({ embeds: [embed] });
    } catch (error) {
      console.error(error);
      const embed = new EmbedBuilder()
        .setTitle('❌ Error')
        .setDescription('An error occurred while generating the forensic report.')
        .setColor(0xff0000)
        .setTimestamp();
      await interaction.reply({ embeds: [embed] });
    }
  }
};
