const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('insiderreport')
    .setDescription('Generate an insider threat report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
    .addUserOption(opt =>
      opt.setName('user').setDescription('Generate report for a specific user')
    ),
  cooldown: 5,
  aliases: ['ireport', 'insiderreport'],
  prefix: true,
  ownerOnly: true,
  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;
    const guild = interaction.guild;

    try {
      if (!member || !member.permissions.has(PermissionFlagsBits.Administrator)) {
        const embed = new EmbedBuilder()
          .setColor(0xed4245)
          .setDescription('You need Administrator permission to use this command.');
        return interaction.reply({ embeds: [embed] });
      }

      const targetUser = isSlash
        ? interaction.options.getUser('user')
        : (args[0] ? guild.members.cache.get(args[0].replace(/[^0-9]/g, ''))?.user : null);

      if (targetUser) {
        const analysis = securityEngine.detectInsiderThreat(guild.id, targetUser.id);
        const risk = securityEngine.calculateRisk(guild.id, targetUser.id);
        const trust = securityEngine.getTrustLevel(guild.id, targetUser.id);
        const profile = securityEngine.getProfile(guild.id, targetUser.id);
        const memberData = guild.members.cache.get(targetUser.id);

        let color = 0x00ff00;
        if (analysis.threatLevel === 'critical') color = 0xff0000;
        else if (analysis.threatLevel === 'high') color = 0xff6600;
        else if (analysis.threatLevel === 'medium') color = 0xffff00;

        const embed = new EmbedBuilder()
          .setTitle(`🕵️ Insider Threat Report: ${targetUser.tag}`)
          .setColor(color)
          .setThumbnail(targetUser.displayAvatarURL())
          .setTimestamp()
          .setFooter({ text: `Guild: ${guild.name}`, iconURL: guild.iconURL() });

        embed.addFields(
          { name: 'User', value: `${targetUser.tag} (${targetUser.id})`, inline: true },
          { name: 'Threat Level', value: `**${analysis.threatLevel.toUpperCase()}**`, inline: true },
          { name: 'Risk Score', value: `**${risk}**/100`, inline: true },
          { name: 'Trust Level', value: `**${trust.label}** (${trust.score}/100)`, inline: true },
          { name: 'Is Trusted', value: trust.isTrusted ? '✅ Yes' : '❌ No', inline: true },
          { name: 'Is Flagged', value: trust.isFlagged ? `⚠️ ${trust.flagReason}` : 'No', inline: true }
        );

        if (memberData) {
          embed.addFields(
            { name: 'Roles', value: `${memberData.roles.cache.size}`, inline: true },
            { name: 'Joined', value: memberData.joinedAt ? `<t:${Math.floor(memberData.joinedTimestamp / 1000)}:R>` : 'Unknown', inline: true }
          );
        }

        if (analysis.indicators.length > 0) {
          embed.addFields({
            name: '⚠️ Threat Indicators',
            value: analysis.indicators.map(i => `• ${i}`).join('\n'),
            inline: false
          });
        }

        embed.addFields({
          name: '📊 Activity Profile',
          value: `Messages: **${profile.messageCount}** | Edits: **${profile.editCount}**\nChannel Creates: **${profile.channelCreates}** | Channel Deletes: **${profile.channelDeletes}**\nRole Changes: **${profile.roleChanges}** | Permission Escalations: **${profile.permissionEscalations}**\nKicks: **${profile.memberKicks}** | Bans: **${profile.memberBans}**`,
          inline: false
        });

        embed.addFields({
          name: '💡 Recommendation',
          value: analysis.recommendation,
          inline: false
        });

        return interaction.reply({ embeds: [embed] });
      }

      const report = securityEngine.generateReport(guild.id);
      let color = 0x00ff00;
      if (report.riskSummary.critical > 0) color = 0xff0000;
      else if (report.riskSummary.high > 0) color = 0xff6600;
      else if (report.riskSummary.medium > 0) color = 0xffff00;

      const embed = new EmbedBuilder()
        .setTitle('🕵️ Insider Threat Report — Server Overview')
        .setDescription(`Generated by ${user.tag}`)
        .setColor(color)
        .setTimestamp()
        .setFooter({ text: `Guild: ${guild.name}`, iconURL: guild.iconURL() });

      embed.addFields(
        { name: 'Total Incidents', value: `**${report.totalIncidents}**`, inline: true },
        { name: 'Unresolved', value: `**${report.unresolvedIncidents}**`, inline: true },
        { name: 'Active Decoys', value: `**${report.activeDecoys}**/${report.totalDecoys}`, inline: true },
        { name: 'Current Stage', value: `**Stage ${report.currentStage.stage}:** ${report.currentStage.name}`, inline: true }
      );

      embed.addFields({
        name: '📊 Risk Distribution',
        value: `🔴 Critical: **${report.riskSummary.critical}**\n🟠 High: **${report.riskSummary.high}**\n🟡 Medium: **${report.riskSummary.medium}**\n🟢 Low: **${report.riskSummary.low}**`,
        inline: true
      });

      if (report.recommendations.length > 0) {
        embed.addFields({
          name: '💡 Recommendations',
          value: report.recommendations.map(r => `• ${r}`).join('\n'),
          inline: false
        });
      }

      if (report.recentIncidents.length > 0) {
        const incidentList = report.recentIncidents.slice(0, 5).map(i =>
          `• ${securityEngine.explainThreat(i)}`
        ).join('\n');
        embed.addFields({
          name: '📋 Recent Incidents',
          value: incidentList.substring(0, 1024),
          inline: false
        });
      }

      return interaction.reply({ embeds: [embed] });
    } catch (error) {
      console.error(error);
      const embed = new EmbedBuilder()
        .setTitle('❌ Error')
        .setDescription('An error occurred while generating the insider threat report.')
        .setColor(0xff0000)
        .setTimestamp();
      await interaction.reply({ embeds: [embed] });
    }
  }
};
