const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');
const { formatDuration } = require('../../../utils/helpers');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('securityreport')
    .setDescription('Generates a full security report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
  cooldown: 5,
  aliases: ['secreport', 'secfullreport'],
  prefix: true,
  ownerOnly: true,
  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;
    const guild = interaction.guild;

    try {
      const report = securityEngine.generateReport(guild.id);
      const stage = report.currentStage;

      const stageColors = {
        0: 0x00ff00,
        1: 0xffff00,
        2: 0xffaa00,
        3: 0xff6600,
        4: 0xff0000,
        5: 0x0099ff
      };

      const stageEmojis = {
        0: '🟢',
        1: '🟡',
        2: '🟠',
        3: '🔴',
        4: '⛔',
        5: '🔄'
      };

      const embed = new EmbedBuilder()
        .setTitle('📋 Full Security Report')
        .setDescription(`Comprehensive security analysis for **${guild.name}**`)
        .setColor(stageColors[stage.stage] || 0x5865f2)
        .setTimestamp()
        .setFooter({ text: `Guild: ${guild.name}`, iconURL: guild.iconURL() })
        .setAuthor({ name: `Generated by ${user.tag}`, iconURL: user.displayAvatarURL() });

      embed.addFields({
        name: '🛡️ Security Stage',
        value: `${stageEmojis[stage.stage] || '⚪'} **${stage.name}** (Stage ${stage.stage})\nActions: ${stage.actions.length > 0 ? stage.actions.join(', ') : 'None'}`,
        inline: false
      });

      embed.addFields({
        name: '🚨 Incident Overview',
        value: `**Total Incidents:** ${report.totalIncidents}\n**Unresolved:** ${report.unresolvedIncidents}\n**Resolved:** ${report.totalIncidents - report.unresolvedIncidents}`,
        inline: true
      });

      embed.addFields({
        name: '🎯 Decoy Status',
        value: `**Total Decoys:** ${report.totalDecoys}\n**Triggered:** ${report.activeDecoys}\n**Active:** ${report.totalDecoys - report.activeDecoys}`,
        inline: true
      });

      const joinVelocityColor = report.joinVelocity.riskLevel === 'critical' ? '🔴' :
        report.joinVelocity.riskLevel === 'high' ? '🟠' :
          report.joinVelocity.riskLevel === 'medium' ? '🟡' : '🟢';

      embed.addFields({
        name: '⚡ Join Velocity (5 min)',
        value: `${joinVelocityColor} **${report.joinVelocity.count}** joins\nVelocity: **${report.joinVelocity.velocity.toFixed(2)}**/min\nStatus: ${report.joinVelocity.isRapid ? 'Rapid' : 'Normal'}`,
        inline: true
      });

      embed.addFields({
        name: '📊 Risk Distribution',
        value: `🔴 Critical (>80): **${report.riskSummary.critical}**\n🟠 High (50-80): **${report.riskSummary.high}**\n🟡 Medium (25-50): **${report.riskSummary.medium}**\n🟢 Low (<25): **${report.riskSummary.low}**`,
        inline: false
      });

      if (report.recentIncidents.length > 0) {
        const recentList = report.recentIncidents.slice(0, 8).map(i => {
          const timeAgo = formatDuration(Date.now() - i.timestamp);
          return `• **${i.type}** - ${timeAgo} ago`;
        }).join('\n');

        embed.addFields({
          name: '📜 Recent Incidents (Last 8)',
          value: recentList,
          inline: false
        });
      }

      if (report.recommendations.length > 0) {
        embed.addFields({
          name: '💡 Recommendations',
          value: report.recommendations.map(r => `• ${r}`).join('\n'),
          inline: false
        });
      }

      const trustStats = {
        totalProfiles: securityEngine.profiles.size,
        highTrust: 0,
        lowTrust: 0,
        flagged: 0
      };

      securityEngine.trustLevels.forEach((data, key) => {
        if (key.startsWith(guild.id)) {
          if (data.level >= 4) trustStats.highTrust++;
          if (data.level <= 1) trustStats.lowTrust++;
          if (data.isFlagged) trustStats.flagged++;
        }
      });

      embed.addFields({
        name: '🤝 Trust Statistics',
        value: `**Total Profiles:** ${trustStats.totalProfiles}\n**High Trust (Lv4+):** ${trustStats.highTrust}\n**Low Trust (Lv1):** ${trustStats.lowTrust}\n**Flagged Users:** ${trustStats.flagged}`,
        inline: true
      });

      embed.addFields({
        name: '⏰ Report Generated',
        value: `<t:${Math.floor(Date.now() / 1000)}:R>`,
        inline: true
      });

      await interaction.reply({ embeds: [embed] });
    } catch (error) {
      console.error(error);
      const embed = new EmbedBuilder()
        .setTitle('❌ Error')
        .setDescription('Failed to generate security report.')
        .setColor(0xff0000)
        .setTimestamp();
      await interaction.reply({ embeds: [embed] });
    }
  }
};