const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const securityEngine = require('../../../utils/securityEngine');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('trustreport')
    .setDescription('Generate trust system report')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
  cooldown: 5,
  aliases: ['trreport', 'trustsummary'],
  prefix: true,
  ownerOnly: true,
  async execute(interaction, args) {
    const isSlash = typeof interaction.isChatInputCommand === 'function' && interaction.isChatInputCommand();
    const member = isSlash ? interaction.member : interaction.guild.members.cache.get(interaction.author?.id);
    const user = isSlash ? interaction.user : interaction.author;
    const guild = interaction.guild;

    if (!member || !member.permissions.has(PermissionFlagsBits.Administrator)) {
      const embed = new EmbedBuilder()
        .setColor(0xed4245)
        .setDescription('You need Administrator permission to use this command.');
      return interaction.reply({ embeds: [embed] });
    }

    try {
      const trustData = [];
      const levelCounts = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
      let totalScore = 0;
      let flaggedCount = 0;
      let trustedCount = 0;

      guild.members.cache.forEach((m) => {
        if (m.user.bot) return;
        const trustLevel = securityEngine.getTrustLevel(guild.id, m.id);
        const risk = securityEngine.calculateRisk(guild.id, m.id);
        trustData.push({ member: m, trust: trustLevel, risk });
        levelCounts[trustLevel.level] = (levelCounts[trustLevel.level] || 0) + 1;
        totalScore += trustLevel.score;
        if (trustLevel.isFlagged) flaggedCount++;
        if (trustLevel.isTrusted) trustedCount++;
      });

      const avgScore = trustData.length > 0 ? (totalScore / trustData.length).toFixed(1) : 0;
      const incidents = securityEngine.getIncidents(guild.id, 100);
      const trustIncidents = incidents.filter(i => i.type === 'trust_modified');

      const policySettings = securityEngine.profiles.get(`trustPolicy:${guild.id}`) || { policy: 'moderate' };
      const alertSettings = securityEngine.profiles.get(`trustAlert:${guild.id}`) || { threshold: 20, enabled: false };
      const decaySettings = securityEngine.profiles.get(`trustDecay:${guild.id}`) || { enabled: false, rate: 2 };

      const riskDistribution = {
        critical: trustData.filter(d => d.risk > 75).length,
        high: trustData.filter(d => d.risk > 50 && d.risk <= 75).length,
        medium: trustData.filter(d => d.risk > 25 && d.risk <= 50).length,
        low: trustData.filter(d => d.risk <= 25).length
      };

      const embed = new EmbedBuilder()
        .setTitle('📊 Trust System Report')
        .setDescription(`Comprehensive trust system report for **${guild.name}**.`)
        .setColor(0x5865f2)
        .setTimestamp()
        .setFooter({ text: `Generated by ${user.tag}`, iconURL: user.displayAvatarURL() })
        .addFields(
          { name: '👥 Total Members', value: `${trustData.length}`, inline: true },
          { name: '📊 Average Trust', value: `${avgScore}/100`, inline: true },
          { name: '✅ Trusted', value: `${trustedCount}`, inline: true },
          { name: '⚠️ Flagged', value: `${flaggedCount}`, inline: true }
        )
        .addFields({
          name: '📊 Trust Distribution',
          value: `🟣 Veteran (5): **${levelCounts[5] || 0}**\n🔵 Trusted (4): **${levelCounts[4] || 0}**\n🟢 Established (3): **${levelCounts[3] || 0}**\n🟡 Known (2): **${levelCounts[2] || 0}**\n⚪ Newcomer (1): **${levelCounts[1] || 0}**`,
          inline: false
        })
        .addFields({
          name: '⚠️ Risk Distribution',
          value: `🔴 Critical (>75): **${riskDistribution.critical}**\n🟠 High (50-75): **${riskDistribution.high}**\n🟡 Medium (25-50): **${riskDistribution.medium}**\n🟢 Low (<25): **${riskDistribution.low}**`,
          inline: false
        })
        .addFields({
          name: '⚙️ Configuration',
          value: `📋 Policy: **${policySettings.policy}**\n🔔 Alerts: ${alertSettings.enabled ? '✅' : '❌'} (Threshold: ${alertSettings.threshold})\n⏳ Decay: ${decaySettings.enabled ? '✅' : '❌'} (${decaySettings.rate}/day)`,
          inline: false
        });

      if (trustIncidents.length > 0) {
        embed.addFields({
          name: '📈 Trust Activity',
          value: `Total trust changes: **${trustIncidents.length}**\nRecent changes: **${trustIncidents.filter(i => Date.now() - i.timestamp < 86400000).length}** (24h)`,
          inline: false
        });
      }

      if (flaggedCount > 0) {
        const flaggedList = trustData.filter(d => d.trust.isFlagged).slice(0, 5).map(d =>
          `⚠️ ${d.member.user.tag} — Score: **${d.trust.score}** (${d.trust.flagReason || 'Flagged'})`
        ).join('\n');
        embed.addFields({ name: '🚨 Flagged Members', value: flaggedList, inline: false });
      }

      const recommendations = securityEngine.generateRecommendations(guild.id, incidents);
      if (recommendations.length > 0) {
        const recs = recommendations.map(r => `• ${r}`).join('\n');
        embed.addFields({ name: '💡 Recommendations', value: recs, inline: false });
      }

      securityEngine.logIncident(guild.id, user.id, 'trust_report_generated', {
        totalMembers: trustData.length,
        averageTrust: avgScore,
        flaggedCount,
        trustedCount
      });

      await interaction.reply({ embeds: [embed] });
    } catch (error) {
      console.error(error);
      const embed = new EmbedBuilder()
        .setTitle('❌ Error')
        .setDescription('Failed to generate trust report.')
        .setColor(0xff0000)
        .setTimestamp();
      await interaction.reply({ embeds: [embed] });
    }
  }
};
